version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: bun
    directories:
      - /web/frontend
      - /test
    schedule:
      interval: weekly
    groups:
      bun-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
